local addonName, ns = ...

ns.DEBUG = false
ns.LOG_LEVEL = 0

ns.LOG_TYPES = {
    INFO = "INFO",
    DEBUG = "DEBUG",
    WARNING = "WARNING",
    ERROR = "ERROR"
}

ns.EVENT_NAMES = {
    PLAYER_LOGIN = "PLAYER_LOGIN",
    PLAYER_ENTERING_WORLD = "PLAYER_ENTERING_WORLD",
    SPELL_CD_UPDATE = "SPELL_UPDATE_COOLDOWN",
    ACTIONBAR_CD_UPDATE = "ACTIONBAR_UPDATE_COOLDOWN",
    SPELLCAST_SUCCEEDED = "UNIT_SPELLCAST_SUCCEEDED",
    SPELLCAST_SENT = "UNIT_SPELLCAST_SENT"
}

ns.UNITS = {
    PLAYER= "player"
}

ns.STRATA = {
    BACKGROUND = "BACKGROUND",
    LOW = "LOW",
    MEDIUM = "MEDIUM",
    HIGH ="HIGH",
    DIALOG ="DIALOG",
    FULLSCREEN ="FULLSCREEN",
    FULLSCREEN_DIALOG= "FULLSCREEN_DIALOG",
    TOOLTIP = "TOOLTIP"
}

ns.TEXTURES = {
    test = "Interface\\AddOns\\GCDBar\\media\\smile.png",
}